### ISSUE TITLE
Configuration for which breakpoint to start horizontal grid

### ISSUE THREAD

**Issue by brandonneil** [radpet/ckeditor-layoutmanager#6]
We have a requirement to keep layouts on xs and sm devices stacked, and start the grids on md device widths. I was thinking it would be nice to make this configurable.

What do you think about the creation of a new configuration option that we can pass in to determine what device size to start the horizontal grid? We could keep the default to xs to maintain backwards compatibility.

Something like
`editor.config.layoutmanager_columnStart = 'md';` which is used to determine what sizes get updated in changeLayoutAction() and the default templates.

At the same time, since using the bootstrap col-{device}-\* classes specify a min-width, we only need to provide one of the classes, so the classes in the default templates for a template could go from
`"col-xs-{size1} col-sm-{size1} col-md-{size1} col-lg-{size1} layout-column"`
to
`"col-" + columnStart + "-{size1} layout-column"`

I am planning to work on something like this if you would consider it.

**Comment by radpet** [comment]
Hello, I totally agree with you. It would definately be more useful and configurable. You can submit a pull request with the feature.

By the way i am planning major refactoring of this plugin to use jquery because using the ckeditor dom api makes the code really unpleasant for reading. What do you think?
Feel free to recommend any other improvements :)
